############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
weight = 2
name = "Handouts"

[[main]]
parent = "Handouts"
name = "Summaries"
url = "/summaries"

[[main]]
parent = "Handouts"
name = "Problem Sets"
url = "/problemsets"

[[main]]
name = "Updates"
url = "/updates"
weight = 3

[[main]]
name = "About"
url = "/about"
weight = 4

# footer menu
[[footer]]
name = "About Me"
url = "/about"
weight = 1


