############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Discussion Board"
url = "/discussions"
weight =2 

[[main]]
weight = 3
name = "Handouts"

[[main]]
parent = "Handouts"
name = "Summaries"
url = "/summaries"

[[main]]
parent = "Handouts"
name = "Problem Sets"
url = "/problemsets"

[[main]]
name = "Updates"
url = "/updates"
weight = 4

[[main]]
name = "About"
url = "/about"
weight = 5

# footer menu
[[footer]]
name = "About Me"
url = "/about"
weight = 1


